name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Install Dependencies
        run: yarn

      - name: Setup CI Git User
        run: |
          git config --global user.email "anapaula.vale6@gmail.com"
          git config --global user.name "aninhabot"

      - name: "Creates Pull Request or Publish to npm"
        id: changesets 
        uses: changesets/action@v1
        with:
          publish: yarn release
          setupGitUser: false
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_BOT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Notify publish success to Slack
        if: steps.changesets.outputs.published == 'true'
        uses: slackapi/slack-github-action@v1.22.0
        with:
          payload: |
            {
              "message": "${{ env.message }}"
            }
        env:
          message: "✅ Successfully published Pluto to NPM. Packages updated: ${{ steps.changesets.outputs.publishedPackages }}"
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify publish failure to Slack
        if: ${{ !steps.changesets.outputs.published }}
        uses: slackapi/slack-github-action@v1.22.0
        with:
          payload: |
            {
              "message": "${{ env.message }}"
            }
        env:
          message: ❌ Something went wrong publishing Pluto to NPM
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}